### ISSUE TITLE
Cannot login with IE 11 and Firefox 52.6.0 (64 bits) on Win10 desktop and my Samsung Note 5 browser

### ISSUE THREAD

**Issue by wannering** [BREDFactory/flex-web-client#25]
When I click on "Envoyer le code" button, the message below appears:
"Adresse mail non valide"

In the console log 
debug: Validating an email : ingrid.wanner@bred.fr  2.c0b440b6.chunk.js:1:757284
debug: Email is correct  2.c0b440b6.chunk.js:1:757284
"debug: Technical error fetching : https://51.145.186.86:443/api/user/login -> TypeError: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkOWYzODQxMTgzOTllMDAyN2VlMDcyYiIsImlhdCI6MTU3MDcxNTc2Mn0.bUBzIGRV6FuivqHYJrEDEa3e2jG0Oz0hM694b9rxTnU
 is an invalid header value."2.c0b440b6.chunk.js:1:757284

**Comment by canatac** [comment]
We split this issue in 3 : 
 This one : IE 11 and Firefox 52.6.0, is closed...
#29 Cannot login with Note 5 device "Samsung Internet" 10.1.01.3
#30 Cannot login with Note 5 device + Chrome
