### ISSUE TITLE
UX - Replace the "Unknow error" message

### ISSUE THREAD

**Issue by wannering** [BREDFactory/flex-web-client#53]
Env: flexoffice.bred.fr 

Context: Chantale on PC took place JO-4-V-RER18. Alex on the phone scans the qrcode from the same place. 
A popup indicates "Unknown error".
Please change the message with "Cette place n'est pas disponible".

**Comment by LePacko** [comment]
i change the message. If you have more idea tell me. 
And if you juts want the message "Cette place n'est pas disponible" close the issue
