### ISSUE TITLE
Remote day display

### ISSUE THREAD

**Issue by ayshiff** [BREDFactory/flex-web-client#9]
- Sometimes remote day display seems broken :     

![Capture d’écran 2019-08-21 à 15 32 19](https://user-images.githubusercontent.com/32459935/63436459-05b59400-c429-11e9-8142-ae859161a2ce.jpg)

**Comment by LePacko** [comment]
practically ok just need to find why the date is update with one day apart

**Comment by LePacko** [comment]
find it ! a problem in the server when the date is parse
